spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/cpstream
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

livekit.ws-url=wss://YOUR_LIVEKIT_PROJECT.livekit.cloud
livekit.api-key=YOUR_LIVEKIT_API_KEY
livekit.api-secret=YOUR_LIVEKIT_API_SECRET

spring.data.redis.host=localhost
spring.data.redis.port=6379

chat.rate-limit.window-seconds=10
chat.rate-limit.max-messages=5

server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=never
spring.security.oauth2.resourceserver.jwt.issuer-uri=${CLERK_ISSUER}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWKS_URL}